// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// checkPTA
LogicalMatrix checkPTA(NumericVector pta_nodes, List points);
RcppExport SEXP _searchPTA_checkPTA(SEXP pta_nodesSEXP, SEXP pointsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type pta_nodes(pta_nodesSEXP);
    Rcpp::traits::input_parameter< List >::type points(pointsSEXP);
    rcpp_result_gen = Rcpp::wrap(checkPTA(pta_nodes, points));
    return rcpp_result_gen;
END_RCPP
}
// get_node_paths
List get_node_paths(List rpart_obj);
RcppExport SEXP _searchPTA_get_node_paths(SEXP rpart_objSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type rpart_obj(rpart_objSEXP);
    rcpp_result_gen = Rcpp::wrap(get_node_paths(rpart_obj));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_searchPTA_checkPTA", (DL_FUNC) &_searchPTA_checkPTA, 2},
    {"_searchPTA_get_node_paths", (DL_FUNC) &_searchPTA_get_node_paths, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_searchPTA(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
