# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

checkPTA <- function(pta_nodes, points) {
    .Call(`_searchPTA_checkPTA`, pta_nodes, points)
}

get_node_paths <- function(rpart_obj) {
    .Call(`_searchPTA_get_node_paths`, rpart_obj)
}

